# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldashboard', '0002_auto_20160816_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
