# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveldashboard', '0003_auto_20160816_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='attending',
        ),
        migrations.AddField(
            model_name='attending',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttendingToTrip', to='traveldashboard.Trip'),
        ),
        migrations.AddField(
            model_name='attending',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AttendingToUser', to='traveldashboard.User'),
        ),
    ]
