# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveldashboard', '0004_auto_20160816_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='datefrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='dateto',
            field=models.DateField(),
        ),
    ]
